### PR TITLE
Update restaurantOwners.controller.js

### PR DESCRIPTION
**Pull request by vitaly-t**
Just one example of how to write much better queries ;)

### CODE REVIEW

**Comment by kayheen** [comment]
Thank you so much for your suggestion!! :)  @vitaly-t

**Comment by vitaly-t** [comment]
u're welcome! missed a letter, now fixed ;)

**Review by wailu — APPROVED** [review]
Thank you ;)

**Comment by wailu** [comment]
Look good! Will merge now; thank you for the suggestion again @vitaly-t !

**Pull request merged**
